# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_HIT = descriptor.Descriptor(
  name='Hit',
  full_name='freequery.index.forward_index.Hit',
  filename='forward_index.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pos', full_name='freequery.index.forward_index.Hit.pos', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TERMHITS = descriptor.Descriptor(
  name='TermHits',
  full_name='freequery.index.forward_index.TermHits',
  filename='forward_index.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='term', full_name='freequery.index.forward_index.TermHits.term', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hits', full_name='freequery.index.forward_index.TermHits.hits', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FORWARDINDEXENTRY = descriptor.Descriptor(
  name='ForwardIndexEntry',
  full_name='freequery.index.forward_index.ForwardIndexEntry',
  filename='forward_index.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='docid', full_name='freequery.index.forward_index.ForwardIndexEntry.docid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='term_hits', full_name='freequery.index.forward_index.ForwardIndexEntry.term_hits', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TERMHITS.fields_by_name['hits'].message_type = _HIT
_FORWARDINDEXENTRY.fields_by_name['term_hits'].message_type = _TERMHITS

class Hit(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HIT

class TermHits(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TERMHITS

class ForwardIndexEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORWARDINDEXENTRY

