# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_POSTING = descriptor.Descriptor(
  name='Posting',
  full_name='freequery.index.inverted_index.Posting',
  filename='freequery/index/inverted_index.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='docid', full_name='freequery.index.inverted_index.Posting.docid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hits', full_name='freequery.index.inverted_index.Posting.hits', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INVERTEDINDEXENTRY = descriptor.Descriptor(
  name='InvertedIndexEntry',
  full_name='freequery.index.inverted_index.InvertedIndexEntry',
  filename='freequery/index/inverted_index.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='term', full_name='freequery.index.inverted_index.InvertedIndexEntry.term', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='postings', full_name='freequery.index.inverted_index.InvertedIndexEntry.postings', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import freequery.index.forward_index_pb2

_POSTING.fields_by_name['hits'].message_type = freequery.index.forward_index_pb2._HIT
_INVERTEDINDEXENTRY.fields_by_name['postings'].message_type = _POSTING

class Posting(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSTING

class InvertedIndexEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVERTEDINDEXENTRY

